### PR TITLE
Feature/test js recipes

### PR DESCRIPTION
**Pull request by 1Eva1987**

### CODE REVIEW

**Comment by codenamehaylz** [comment]
Hi Ieva, your branch is missing the input form section in the html - you will need to pull the latest code from main first and resolve conflicts locally before sending another pull request

**Comment by codenamehaylz** [comment]
Also when testing the code I noticed that the 'show less' button works the first time but then it is hidden and doesn't show up for any other cards that I open. I found that you can fix this by just putting `btnClose.show();` at the beginning of the click event for the 'see full recipe' button :)

**Comment by 1Eva1987** [comment]
Hi, Hayley that is is only testing bit as described in the issue i have created for this branch so thats why it is commented out to not effect the app, ass soon as it is merged i am creating new issue to make the code work based on users input and make sure all the buttons looks good and works . And yes i have pulled the latest now :)

**Comment by codenamehaylz** [comment]
That's fine :)
It looks like the code in the pull request is still missing the search forms? I can't merge the pull request yet as it will delete those forms.
If you've already put the code from main into your branch then you might need to commit those changes and do another push using `git push origin feature/test-js-recipes`, in order for it to update this pull request

**Comment by 1Eva1987** [comment]
I did pull and commit so all the changes in html is now visible with my changes but when i push i cant see it in git hub...?
\

**Comment by codenamehaylz** [comment]
I can see it in github, when looking at the code it only shows you lines that you have changed, but if you expand to see the whole code, you can now see the forms. It looks good to me so I'm happy to go ahead and merge it.
I have a pull request open too but don't merge that yet as I will need to update it with this code

**Pull request merged**
